Added the Skywalker X8 Quadplane
ArduPilot/SITL_Models pull request #125
Opened 2024-05-01 12:27 UTC by Georacer

# Summary

This PR adds a Skywalker X8 Quadplane.

It is the product of [this blog post](https://discuss.ardupilot.org/t/creating-a-realflight-model-with-blender/116967).

# Known issues

1. The CG to fly the airplane is quite far forward for the X-center of the MC thrusters. A noticeable pitch-forward after MC takeoff is to be expected.
2. While Autotune succeeded for Roll and Pitch, it doesn't finish on yaw. I'm not sure why. MC doesn't fly that bad, though.
3. Autotune for FW was carried out.
5. Most importantly, the UA is very unstable during a transition.
  * In forward-transition, it will wobble a lot (lack of yaw stability) until it reaches 100kph. It is advised to have WOT throttle in FBWA while attempting it.
  * In backwards-transition, abandon all hope...

2024-05-01 12:28 UTC, Georacer commented
@tridge here's the PR!
Please read the README.md for channel functions.

I'd greatly appreciate help and insights in taming the transition.

2024-05-01 15:50 UTC, Quadzilla805 requested changes

2024-05-01 20:39 UTC, Georacer commented on RealFlight/Released_Models/QuadPlanes/Skywalker X8 QuadPlane/CAD/x8_vtol.blend
I know it's confusing, but that's actually the name of the airframe, and a pretty legendary at that: http://skywalkermodel.com/en/76.html
I don't feel right changing it just because it reminds of a multicopter configuration.

About the polygons, yeah, I won't argue with you that there are bad polygons. The original file I got was an .STL of 100.000 triangle faces and I automatically simplified it to get to a more reasonable face count.
I don't know of a way to both reduce the face count **and** have a nice quality surface consistency.
Do you have any advice on that?

2024-05-02 12:00 UTC, Georacer commented
I updated the Blender, FBX and .RFX models with isso's (from Discord) changes.
The elevons should deflect correctly now.
Also the in-game filename after importing the .RFX should display "Skywalker X8 Quadplane", instead of "x8_vtol".

2024-05-02 12:12 UTC, MichelleRos commented
Maybe remove the .blend1 file from the PR, as it's just a backup of the .blend file (it should just be the previous save).

2024-05-04 04:22 UTC, tridge commented
see comments in the simulation channel thread on discord

2024-05-09 21:27 UTC, Georacer commented
I retuned manually and... I cheated: I moved the actual booms much more forward, so that the MC X-center is close to the CoM.
![image](https://github.com/ArduPilot/SITL_Models/assets/3149996/d18a33ca-508a-4967-9425-cd0847189a87)
I don't believe this design can fly without this fix.

The back and forth transitions are now always successful. Not the smoothest you've seen still. Suggestions are welcome.

There is still some roll oscillation when flying MC at very high speeds (~100km/h), but I don't think it's an issue.

If you guys don't want to have this model in the "Released" folder because of the cheat, that's OK. We can move it elsewhere, e.g "WIP".

2024-05-25 20:56 UTC, merged