Add Addiction_3D to release models
ArduPilot/SITL_Models pull request #58
Opened 2021-12-24 16:49 UTC by Hwurzburg

2021-12-24 21:16 UTC, kd0aij requested changes
Very little roll/pitch authority in QHOVER. Is this the best it can do?
FBWA seems good
ACRO with yaw rate at 60 deg/sec seems really weak on yaw authority compared to FBWA

2021-12-24 21:16 UTC, kd0aij commented on RealFlight/Released_Models/QuadPlanes/Tailsitters/Addiction_3D/README.md
> +* Wing Span....... 23 (in)
the RealFlight physics for this model has half-span of 585mm which equates to a full span of 46"
But the aileron length is 640mm ???  probably should be 580mm

2021-12-25 20:46 UTC, kd0aij commented
Tune seems good in QHOVER, FBWA and ACRO. I'm assuming my frame rate is too low for QACRO though since I get severe roll oscillations.

2021-12-26 13:44 UTC, Hwurzburg commented
flies okay for me...whats your frame rate?

2021-12-28 16:38 UTC, Hwurzburg commented
@kd0aij thanks for testing and helping improve....

2021-12-28 16:39 UTC, merged